ALTER TABLE person
ADD COLUMN IF NOT EXISTS death_year INTEGER;

ALTER TABLE person
ADD COLUMN IF NOT EXISTS phone_number VARCHAR(50);

ALTER TABLE person
ADD COLUMN IF NOT EXISTS social_links JSONB;

ALTER TABLE person
ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE person
ADD COLUMN IF NOT EXISTS phone_verified_at TIMESTAMPTZ;
